site_name: Terre Natale
extra_css:
  - css/extra.css
  - css/print.css
  - css/custom.css
plugins:
  - search
nav:
  - Accueil: index.md
  - Cr√©ation: creation/creation/index.html
  - Castes: castes/castes/index.html
  - Ethnies: ethnies/ethnies/index.html
  - Patch: rules/confrontations/index.html
  - Magies:
    - Ombre: magies/ombre.html
    - Impie:  magies/impie.html
    - Toxique:  magies/toxique.html
    - Arcane:  magies/arcane.html
    - Magie:  magies/magie.html
    - Acier:  magies/acier.html
    - Guerre:  magies/guerre.html
    - Chaos:  magies/chaos.html
    - Vide:  magies/vide.html
    - Terre:  magies/terre.html
  - Outils:
    - Vitals: tools/vitals/index.html
    - Stats: tools/stats/index.html
theme:
  name: "material"
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
markdown_extensions:
  - attr_list